apiVersion: apps/v1
kind: Deployment
metadata:
  name: bindrocket-admin-frontend-dev
  replicas: 1
  selector:
    matchLabels:
      app: bindrocket-admin-frontend-dev
  template:
    metadata:
      labels:
        app: bindrocket-admin-frontend-dev
    spec:
      nodeSelector:
        role: worker
      containers:
        - name: bindrocket-admin-frontend-dev
          image: ${ECR_REPOSITORY}/${BINDROCKET_ADMIN_FRONTEND_DEV_IMAGE}:BUILD_NUMBER_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: bindrocket-admin-frontend-dev
  labels:
    app: bindrocket-admin-frontend-dev
spec:
  selector:
    app: bindrocket-admin-frontend-dev
  ports:
    - name: backend
      port: 3000
      targetPort: 80
  type: ClusterIP
